config/routes.rb
Rails.application.routes.draw do

  resources :tweets
  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(params.require(:tweet).permit(:author, :body))
    if @tweet.save
      redirect_to "/tweets"
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twetter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/_new.html.erb
<%= form_for object do |f| %>
        <p><%= f.label :body %>:</p>
        <p><%= f.text_field :body %></p>
        <p><%= f.label :author %> </p>
        <p><%= f.text_field :author %> </p>
        <p><%= f.submit %></p>
      <% end %>

app/views/tweets/index.html.erb
<body>
<div class='container'>
  <div class="row">
    <div class='sidebar col-lg-4'>
      <%= form_for @tweet do |f| %>
              <p><%= f.label :body %>:</p>
              <p><%= f.text_field :body %></p>
              <p><%= f.label :author %> </p>
              <p><%= f.text_field :author %> </p>
              <p><%= f.submit %></p>
            <% end %>
    </div>

    <div class="main col-lg-8">
      <h1> Tweet Stream </h1>
      <% @tweets.each do |tweet| %>
        <h3> <%= link_to tweet.body, tweet_path(tweet.id) %> </h3>
        by:
        <%= tweet.author %>






        
      <% end %>

    </div>


  </div>
</div>


</body>

app/views/tweets/show.html.erb
  <%= @tweet.author %>
  <%= @tweet.body %>

<button type="button" class="btn btn-lg btn-danger" data-toggle="popover"
title="Popover title"
data-content= <%= @tweet.author %>
<%= @tweet.body %>>Click to toggle popover</button>